name: Actions smoke test

on:
  push:
    branches:
      - ci/actions-test
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GitHub Actions works"
